#!/usr/bin/env bash
# ============================================================================
#  Hyper Liquid Trader — one-shot installer
#  Clones/uses the trading bot, installs every dependency (incl. Python),
#  asks for the vital secrets up front, then boots both bots under screen.
#
#  Run:  bash setup.sh
#  (if you already have the repo, run it from inside the repo root)
# ============================================================================
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/matildameta/trading-bot-hl.git}"
REPO_DIR="${REPO_DIR:-trading-bot-hl}"
PY_MIN="3.10"

echo "╔══════════════════════════════════════════════════════════╗"
echo "║   Hyper Liquid Trader — Installer                        ║"
echo "╚══════════════════════════════════════════════════════════╝"

# ---------------------------------------------------------------------------
# 1) VITAL INPUTS (asked FIRST, before anything else)
# ---------------------------------------------------------------------------
echo
echo "▶ Step 1/6 — اطلاعات حیاتی را وارد کنید"
echo "  (این مقادیر در config.yaml نوشته می‌شوند و به گیت‌هاب نمی‌روند)"
echo

read -rsp "🔑 کلید خصوصی Hyperliquid (secret_key): " HL_SECRET; echo
read -rp "🌐 شبکه پیش‌فرض (testnet/mainnet) [testnet]: " HL_NET; HL_NET="${HL_NET:-testnet}"
read -rsp "🤖 توکن ربات تلگرام (پنل/کنترل): " TG_PANEL; echo
read -rsp "📣 توکن ربات تلگرام (گزارش‌گر): " TG_REPORT; echo
read -rp "💬 آیدی چت تلگرام مدیر (عددی): " TG_CHAT; echo
read -rp "🧠 مدل پیش‌فرض LLM [anthropic/claude-sonnet-4]: " LLM_MODEL
LLM_MODEL="${LLM_MODEL:-anthropic/claude-sonnet-4}"
read -rsp "🔓 کلید OpenRouter (برای مدل‌های LLM): " OR_KEY; echo

# ---------------------------------------------------------------------------
# 2) SYSTEM PREREQUISITES
# ---------------------------------------------------------------------------
echo; echo "▶ Step 2/6 — بررسی و نصب پیش‌نیازهای سیستم"
need_apt=()
command -v git >/dev/null 2>&1 || need_apt+=(git)
command -v python3 >/dev/null 2>&1 || need_apt+=(python3)
command -v gcc >/dev/null 2>&1 || need_apt+=(build-essential)
command -v python3.12 >/dev/null 2>&1 || command -v python3.11 >/dev/null 2>&1 || need_apt+=(python3.12)
if [ ${#need_apt[@]} -gt 0 ]; then
  echo "  نصب: ${need_apt[*]}"
  sudo apt-get update -y
  sudo apt-get install -y "${need_apt[@]}"
fi
PYBIN="$(command -v python3.12 || command -v python3.11 || command -v python3)"
echo "  Python: $($PYBIN --version 2>&1)"

# ---------------------------------------------------------------------------
# 3) GET THE CODE
# ---------------------------------------------------------------------------
echo; echo "▶ Step 3/6 — دریافت کد"
if [ -d "$REPO_DIR/.git" ]; then
  echo "  repo موجود است، به‌روزرسانی…"
  git -C "$REPO_DIR" pull --ff-only
else
  git clone "$REPO_URL" "$REPO_DIR"
fi
cd "$REPO_DIR"

# ---------------------------------------------------------------------------
# 4) PYTHON VENV + DEPENDENCIES
# ---------------------------------------------------------------------------
echo; echo "▶ Step 4/6 — ساخت محیط مجازی و نصب وابستگی‌ها"
if [ ! -d .venv ]; then
  "$PYBIN" -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate
pip install --quiet --upgrade pip
pip install --quiet -r core_engine/requirements.txt -r control_bot/requirements.txt
# pandas-ta is sometimes missing on PyPI for newer pythons — fall back to git
python -c "import pandas_ta" 2>/dev/null || pip install --quiet "git+https://github.com/twopirllc/pandas-ta.git@main"

# ---------------------------------------------------------------------------
# 5) WRITE config.yaml (from example, inject secrets)
# ---------------------------------------------------------------------------
echo; echo "▶ Step 5/6 — نوشتن config.yaml"
write_cfg () {
  local dir="$1"
  cat > "$dir/config.yaml" <<EOF
# Auto-generated by setup.sh — DO NOT commit this file.
network: $HL_NET
hyperliquid:
  account_address: ""
  secret_key: "$HL_SECRET"
  $HL_NET:
    account_address: ""
    secret_key: "$HL_SECRET"
llm:
  default_model: "$LLM_MODEL"
  api_keys:
    openrouter: "$OR_KEY"
  request_timeout_seconds: 60
telegram:
  bot_token: "$TG_PANEL"
  chat_id: "$TG_CHAT"
EOF
  chmod 600 "$dir/config.yaml"
}
write_cfg core_engine
# control bot only needs telegram token + chat id + shared db path
cat > control_bot/config.yaml <<EOF
# Auto-generated by setup.sh — DO NOT commit this file.
telegram_bot_token: "$TG_PANEL"
allowed_chat_id: "$TG_CHAT"
shared_db_path: "../shared/bot_state.db"
network_label: $HL_NET
EOF
chmod 600 control_bot/config.yaml
echo "  config.yaml نوشته شد (chmod 600)."

# ---------------------------------------------------------------------------
# 6) BOOT UNDER SCREEN
# ---------------------------------------------------------------------------
echo; echo "▶ Step 6/6 — راه‌اندازی با screen"
launch () {
  local name="$1" dir="$2" cmd="$3"
  if screen -list 2>/dev/null | grep -q "\.$name\b"; then
    echo "  screen '$name' از قبل بالاست (دست‌نخورده می‌ماند)."
  else
    screen -dmS "$name" bash -c "cd $(pwd)/$dir && source ../.venv/bin/activate && $cmd 2>&1 | tee ../$name.log"
    echo "  screen '$name' راه افتاد."
  fi
}
# traderbot MUST run from core_engine/ (module is core_engine/src/main.py)
launch traderbot  core_engine ".venv/bin/python -m src.main"
# traderctl MUST run from control_bot/ (module is control_bot/src/bot.py)
launch traderctl  control_bot ".venv/bin/python -m src.bot"

echo
echo "✅ نصب کامل شد."
echo "  مشاهده لاگ‌ها:  screen -r traderbot   /   screen -r traderctl"
echo "  خارج شدن از لاگ (بدون توقف):  Ctrl+A سپس D"
echo "  توقف:  screen -S traderbot -X quit"
